# Generated by Django 6.0.3 on 2026-04-03 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_alter_user_email'),
        ('optics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='optic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='optics.optic'),
        ),
    ]
