# Generated by Django 6.0.3 on 2026-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_cost_total_sale_profit_saleitem_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='pending_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
