# Generated by Django 6.0.3 on 2026-04-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optic',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='slug',
            field=models.SlugField(default='optic-temp', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optic',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='theme_colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
