# Generated by Django 6.0.3 on 2026-04-03 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='record',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='record',
            name='reason',
        ),
        migrations.AddField(
            model_name='record',
            name='alt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='blurred_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='burning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='conjunctivitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='di',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='far_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='frame_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='frame_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='frame_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='frame_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='general_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='glasses_use_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='glaucoma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='headache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='heart_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='irritation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='keratoconus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='lens_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='lens_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='near_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='ocular_trauma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='optometrist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optometrist_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='photophobia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='pterygium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_od_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_od_axis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_od_cyl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_od_sph',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_oi_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_oi_axis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_oi_cyl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_oi_sph',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_od_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_od_axis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_od_cyl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_od_sph',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_oi_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_oi_axis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_oi_cyl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rx_prev_oi_sph',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='strabismus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='stye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='surgeries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tearing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='uses_glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='uveitis',
            field=models.BooleanField(default=False),
        ),
    ]
