# Generated by Django 6.0.3 on 2026-04-04 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_record_diagnosis_remove_record_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('visual_acuity_without_lenses_od', models.CharField(blank=True, max_length=20, null=True)),
                ('visual_acuity_without_lenses_oi', models.CharField(blank=True, max_length=20, null=True)),
                ('visual_acuity_with_lenses_od', models.CharField(blank=True, max_length=20, null=True)),
                ('visual_acuity_with_lenses_oi', models.CharField(blank=True, max_length=20, null=True)),
                ('visual_acuity_with_lenses_ao', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_od_sph', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_od_cyl', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_od_axis', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_oi_sph', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_oi_cyl', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_oi_axis', models.CharField(blank=True, max_length=20, null=True)),
                ('rx_add', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('lens_type', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optometrist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='records.record')),
            ],
        ),
    ]
